# EDITADO FEV-13
"""
Django settings for arqcalc_django project.
Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%f6%#9iu@$2ux^92+ugrl#pfi96d%tfxoq&ic-(r4r2hfsr3hd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [  'django.contrib.admin',
                    'django.contrib.auth',
                    'django.contrib.contenttypes',
                    'django.contrib.sessions',
                    'django.contrib.messages',
                    'django.contrib.staticfiles',
                    'django.contrib.humanize', ###
                    'arqcalc_webapp'
                ]

MIDDLEWARE     = [  'django.middleware.security.SecurityMiddleware',
                    'django.contrib.sessions.middleware.SessionMiddleware',
                    'django.middleware.common.CommonMiddleware',
                    'django.middleware.csrf.CsrfViewMiddleware',
                    'django.contrib.auth.middleware.AuthenticationMiddleware',
                    'django.contrib.messages.middleware.MessageMiddleware',
                    'django.middleware.clickjacking.XFrameOptionsMiddleware',
                ]

ROOT_URLCONF   = 'arqcalc_django.urls'
TEMPLATES      = [{
                    'BACKEND': 'django.template.backends.django.DjangoTemplates',
                    'DIRS': [BASE_DIR / 'templates'],
                    'APP_DIRS': True,
                    'OPTIONS': {
                        'context_processors': [
                            'django.template.context_processors.request',
                            'django.contrib.auth.context_processors.auth',
                            'django.contrib.messages.context_processors.messages',
                        ],
                    },
                }]

WSGI_APPLICATION = 'arqcalc_django.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.mysql',  # ou 'django.db.backends.postgresql' se for postgres
#        'NAME': 'u712489129_teste_arqcalc',
#        'USER': 'u712489129_teste_arqcalc',
#        'PASSWORD': 'Teste@2022',
#        'HOST': '185.214.126.7',  # ou IP do banco
#        'PORT': '3306',       # padrão MySQL, pode mudar
#    }
#}

DATABASES = {"default": {"ENGINE": "django.db.backends.sqlite3", "NAME": "mydatabase"}}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'pt-br'
TIME_ZONE     = 'America/Sao_Paulo'
USE_I18N      = True
USE_L10N      = True
USE_TZ        = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL       = '/static/'
STATICFILES_DIRS = [BASE_DIR / "arqcalc_webapp" / "static"]  # ou equivalente

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD  = 'django.db.models.BigAutoField'
LOGOUT_REDIRECT_URL = '/'  # Ou 'login' ou qualquer página

#-----------------------------------------------------------------#
# Configurações de E-mail Hostinger
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST    = 'smtp.hostinger.com'
EMAIL_PORT    = 465    # Porta padrão para SSL
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False  # Hostinger prefere SSL na porta 465

import os
from dotenv import load_dotenv
# Carrega as variáveis do arquivo .env
load_dotenv()

EMAIL_HOST_USER     = 'contato@arqcalc.com.br'
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

# O e-mail que aparecerá como remetente
DEFAULT_FROM_EMAIL  = 'ArqCalc <contato@arqcalc.com.br>'
SERVER_EMAIL        = 'contato@arqcalc.com.br' #endereço usado pelo Django para enviar mensagens de erro automáticas do sistema